import Head from "next/head";
import { motion } from "framer-motion";
import { useSession, useToggle } from "~/hooks";
import {
	IconHelpSquare,
	IconHome2,
	IconLayoutBottombar,
	IconLayoutBottombarExpand,
	IconLogin,
	IconLogout2,
	IconPhoto,
	IconTable,
	TablerIconsProps,
} from "@tabler/icons-react";
import { Toaster } from "react-hot-toast";
import { classNames } from "~/utils/classNames";
import { useMemo } from "react";
import Link from "next/link";
import axios from "axios";

interface AppLayoutProps {
	children: React.ReactNode;
}

const navWrapVariants = {
	open: {
		scaleY: 1,
		transition: {
			when: "beforeChildren",
			staggerChildren: 0.1,
		},
	},
	closed: {
		scaleY: 0,
		transition: {
			when: "afterChildren",
			staggerChildren: 0.1,
		},
	},
};

const navItemVariants = {
	open: {
		opacity: 1,
		y: 0,
		transition: {
			when: "beforeChildren",
		},
	},
	closed: {
		opacity: 0,
		y: -7,
		transition: {
			when: "afterChildren",
		},
	},
};

export function AppLayout({ children }: AppLayoutProps): JSX.Element {
	const [isOpen, toggleIsOpen] = useToggle(false);
	const { data: session, ...sessionRest } = useSession();

	const logout = useMemo(() => {
		return function () {
			axios.post("/api/auth/logout", null, { withCredentials: true });
		};
	}, []);

	return (
		<>
			<Head>
				<title>Project-Memory</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo.png" />
				
			</Head>
			<main className="h-screen w-screen scrollbar-none bg-dark text-light overflow-y-scroll relative">
				{children}
				<Toaster />

				<motion.div
					className="fixed bottom-8 right-12"
					animate={isOpen ? "open" : "closed"}
				>
					<motion.button
						className="text-purple-400 p-2 bg-gray-600 w-fit rounded-lg "
						onClick={toggleIsOpen}
						whileHover={{ scale: 1.1 }}
						whileTap={{ scale: 0.9 }}
					>
						{isOpen ? (
							<IconLayoutBottombarExpand className="text-current" size={36} />
						) : (
							<IconLayoutBottombar className="text-current" size={36} />
						)}
					</motion.button>

					<motion.ul
						className="absolute top-0 w-fit bg-light bg-opacity-20 backdrop-blur-[8px] p-2 rounded-lg whitespace-nowrap"
						initial={navWrapVariants.closed}
						variants={navWrapVariants}
						style={{
							originY: "bottom",
							translateX: "-50%",
							translateY: "-110%",
						}}
					>
						<NavItem text="Home" uri="/" icon={IconHome2} className="md:hover:bg-purple-200 hover:text-purple-800 " />
						<NavItem text="Guide" uri="/guide" icon={IconHelpSquare} className="md:hover:bg-purple-200 hover:text-purple-800 " />
						<NavItem text="Gallery" uri="/gallery" icon={IconPhoto} className="md:hover:bg-purple-200 hover:text-purple-800 " />
						<NavItem text="About me" uri="/me" icon={IconTable} className="md:hover:bg-purple-200 hover:text-purple-800 " />
						{session ? (
							<NavItem
								text="Logout"
								uri="/api/logout"
								icon={IconLogout2}
								className="text-red-600 font-medium "
							/>
						) : (
							<NavItem
								text="Login"
								uri="/auth/login"
								icon={IconLogin}
								className="text-purpureus font-medium "
							/>
						)}
					</motion.ul>

					{/* <motion.div
						initial={navWrapVariants.closed}
						variants={navWrapVariants}
						className="absolute left-0 bottom-0 bg-light bg-opacity-20 backdrop-blur-[8px] p-2 rounded-lg whitespace-nowrap text-red-600"
						style={{ translateX: "-110%", translateY: "" }}
					>
						Logout
					</motion.div> */}
				</motion.div>
			</main>
		</>
	);
}

interface NavItemProps {
	text: string;
	uri: string;
	icon?: (props: TablerIconsProps) => JSX.Element;
	className?: string;
	handleCick?: () => void;
}

function NavItem({
	text,
	icon: Icon,
	uri,
	className,
}: NavItemProps): JSX.Element {
	return (
		<motion.li
			className={classNames(
				className ? className : "",
				"p-2 rounded-md flex justify-start text-current text-base items-center gap-2 font-semibold hover:font-semibold"
			)}
			variants={navItemVariants}
		>
			<motion.span>{Icon && <Icon />}</motion.span>
			<Link href={uri}>{text}</Link>
		</motion.li>
	);
}
